package io.github.yajuhua.download.downloader.ytdlp.json.channel;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@NoArgsConstructor
@Data
public class Entries {
    @SerializedName(value = "id")
    private String id;
    @SerializedName(value = "title")
    private String title;
    @SerializedName(value = "formats")
    private List<Formats> formats;
    @SerializedName(value = "thumbnails")
    private List<Thumbnails> thumbnails;
    @SerializedName(value = "thumbnail")
    private String thumbnail;
    @SerializedName(value = "description")
    private String description;
    @SerializedName(value = "channel_id")
    private String channelId;
    @SerializedName(value = "channel_url")
    private String channelUrl;
    @SerializedName(value = "duration")
    private Integer duration;
    @SerializedName(value = "view_count")
    private Double viewCount;
    @SerializedName(value = "average_rating")
    private Object averageRating;
    @SerializedName(value = "age_limit")
    private Double ageLimit;
    @SerializedName(value = "webpage_url")
    private String webpageUrl;
    @SerializedName(value = "categories")
    private List<String> categories;
    @SerializedName(value = "tags")
    private List<?> tags;
    @SerializedName(value = "playable_in_embed")
    private Boolean playableInEmbed;
    @SerializedName(value = "live_status")
    private String liveStatus;
    @SerializedName(value = "release_timestamp")
    private Double releaseTimestamp;
    @SerializedName(value = "_format_sort_fields")
    private List<String> formatSortFields;
    @SerializedName(value = "automatic_captions")
    private AutomaticCaptions automaticCaptions;
    @SerializedName(value = "subtitles")
    private Subtitles subtitles;
    @SerializedName(value = "comment_count")
    private Double commentCount;
    @SerializedName(value = "chapters")
    private Object chapters;
    @SerializedName(value = "heatmap")
    private Object heatmap;
    @SerializedName(value = "like_count")
    private Double likeCount;
    @SerializedName(value = "channel")
    private String channel;
    @SerializedName(value = "channel_follower_count")
    private Double channelFollowerCount;
    @SerializedName(value = "channel_is_verified")
    private Boolean channelIsVerified;
    @SerializedName(value = "uploader")
    private String uploader;
    @SerializedName(value = "uploader_id")
    private String uploaderId;
    @SerializedName(value = "uploader_url")
    private String uploaderUrl;
    @SerializedName(value = "upload_date")
    private String uploadDate;
    @SerializedName(value = "availability")
    private String availability;
    @SerializedName(value = "original_url")
    private String originalUrl;
    @SerializedName(value = "webpage_url_basename")
    private String webpageUrlBasename;
    @SerializedName(value = "webpage_url_domain")
    private String webpageUrlDomain;
    @SerializedName(value = "extractor")
    private String extractor;
    @SerializedName(value = "extractor_key")
    private String extractorKey;
    @SerializedName(value = "playlist_count")
    private Object playlistCount;
    @SerializedName(value = "playlist")
    private String playlist;
    @SerializedName(value = "playlist_id")
    private String playlistId;
    @SerializedName(value = "playlist_title")
    private String playlistTitle;
    @SerializedName(value = "playlist_uploader")
    private String playlistUploader;
    @SerializedName(value = "playlist_uploader_id")
    private String playlistUploaderId;
    @SerializedName(value = "n_entries")
    private Double nEntries;
    @SerializedName(value = "playlist_index")
    private Double playlistIndex;
    @SerializedName(value = "__last_playlist_index")
    private Double lastPlaylistIndex;
    @SerializedName(value = "playlist_autonumber")
    private Double playlistAutonumber;
    @SerializedName(value = "display_id")
    private String displayId;
    @SerializedName(value = "fulltitle")
    private String fulltitle;
    @SerializedName(value = "duration_string")
    private String durationString;
    @SerializedName(value = "release_date")
    private String releaseDate;
    @SerializedName(value = "release_year")
    private Double releaseYear;
    @SerializedName(value = "is_live")
    private Boolean isLive;
    @SerializedName(value = "was_live")
    private Boolean wasLive;
    @SerializedName(value = "requested_subtitles")
    private Object requestedSubtitles;
    @SerializedName(value = "_has_drm")
    private Object hasDrm;
    @SerializedName(value = "epoch")
    private Double epoch;
    @SerializedName(value = "requested_downloads")
    private List<RequestedDownloads> requestedDownloads;
    @SerializedName(value = "requested_formats")
    private List<RequestedFormats> requestedFormats;
    @SerializedName(value = "format")
    private String format;
    @SerializedName(value = "format_id")
    private String formatId;
    @SerializedName(value = "ext")
    private String ext;
    @SerializedName(value = "protocol")
    private String protocol;
    @SerializedName(value = "language")
    private Object language;
    @SerializedName(value = "format_note")
    private String formatNote;
    @SerializedName(value = "filesize_approx")
    private Double filesizeApprox;
    @SerializedName(value = "tbr")
    private Double tbr;
    @SerializedName(value = "width")
    private Double width;
    @SerializedName(value = "height")
    private Double height;
    @SerializedName(value = "resolution")
    private String resolution;
    @SerializedName(value = "fps")
    private Double fps;
    @SerializedName(value = "dynamic_range")
    private String dynamicRange;
    @SerializedName(value = "vcodec")
    private String vcodec;
    @SerializedName(value = "vbr")
    private Double vbr;
    @SerializedName(value = "stretched_ratio")
    private Object stretchedRatio;
    @SerializedName(value = "aspect_ratio")
    private Double aspectRatio;
    @SerializedName(value = "acodec")
    private String acodec;
    @SerializedName(value = "abr")
    private Double abr;
    @SerializedName(value = "asr")
    private Double asr;
    @SerializedName(value = "audio_channels")
    private Double audioChannels;
}
